name: llamagen-cosmos
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.11.5
  - pytorch=2.3.1
  - torchvision=0.18.1
  - cudatoolkit=12.1
  - ninja
  - pip
  - pip:
    - accelerate==0.33.0
    - deepspeed==0.14.4
    - diffusers==0.30.0.dev0
    - einops==0.8.0
    - huggingface-hub==0.24.3
    - numpy==1.26.4
    - pillow==10.4.0
    - peft==0.11.1
    - transformers==4.23.1
    - wandb==0.18.7
    - webdataset==0.2.86
    - torch-optimizer==0.3.0
    - torchmetrics==1.3.2
    - triton==2.3.1
    - ftfy==6.2.0
    - tensorboard==2.15.2
    - omegaconf==2.0.6
    - pyyaml
    - psutil
    - packaging
    - safetensors==0.4.3
